### ISSUE TITLE
Todo for counter manager

### ISSUE THREAD

**Issue by MarcelJurtz** [MarcelJurtz/LifeCounter#23]
- [x] Wrap up counter manager to always use 4 players, no matter what gamemode is currently active
- [x] Add naming customization option for all for players
- [x] Add an option to remove a player completely
- [x] Add an option to remove a counter
- [x] Add an option to increase / decrease a counters value. This should be possible in a quick, easy and intuitive way
- [x] Add useful naming conventions on methods for view & presenter

**Comment by MarcelJurtz** [comment]
Closed by 946f933f0e1d5d193bf44298d918c8cca56068f3
